version: "3.8"
services:
  wscr:
    container_name: wscr1
    build: ~/sw/python/web_collector
    volumes: 
    - ~/sw/python/web_collector:/usr/code
    ports: 
    - "5000:5000"
    #command: /usr/bin/run
  wsfront:
    container_name: wsfront1
    build: ~/sw/javascript/web_collector_front
    volumes: 
    - ~/sw/javascript/web_collector_front:/usr/app
    ports: 
    - "8080:8080"
    #command: /usr/bin/run
