"""Add web id

Revision ID: 172144ccb8ab
Revises: b741806363e4
Create Date: 2020-08-16 11:37:35.661679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '172144ccb8ab'
down_revision = 'b741806363e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('homes', sa.Column('web_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('homes', 'web_id')
    # ### end Alembic commands ###
