"""Add price

Revision ID: 1907bc1b102f
Revises: 172144ccb8ab
Create Date: 2020-08-16 12:03:20.508097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1907bc1b102f'
down_revision = '172144ccb8ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('homes', sa.Column('price', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('homes', 'price')
    # ### end Alembic commands ###
