"""Add image and adv url

Revision ID: 344b239012f6
Revises: 1907bc1b102f
Create Date: 2020-09-04 16:52:39.017652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '344b239012f6'
down_revision = '1907bc1b102f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('homes', sa.Column('adv_url', sa.String(), nullable=True))
    op.add_column('homes', sa.Column('image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('homes', 'image')
    op.drop_column('homes', 'adv_url')
    # ### end Alembic commands ###
