"""Add comments column

Revision ID: 7b4d56ad92bc
Revises: 984187bda738
Create Date: 2020-12-07 18:06:05.557477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b4d56ad92bc'
down_revision = '984187bda738'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('homes', sa.Column('comment', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('homes', 'comment')
    # ### end Alembic commands ###
