"""Add archieving column

Revision ID: 984187bda738
Revises: 344b239012f6
Create Date: 2020-09-27 12:34:33.642915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '984187bda738'
down_revision = '344b239012f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('homes', sa.Column('archived', sa.Integer(), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('homes', 'archived')
    # ### end Alembic commands ###
