"""MySql database creation

Revision ID: da0c03d13a85
Revises: 
Create Date: 2021-01-24 11:10:48.995561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da0c03d13a85'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('homes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(length=10000), nullable=True),
    sa.Column('date_created', sa.String(length=50), nullable=True),
    sa.Column('date_found', sa.String(length=50), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.Column('web_id', sa.String(length=20), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('image', sa.Text(length=10000), nullable=True),
    sa.Column('adv_url', sa.String(length=500), nullable=True),
    sa.Column('archived', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('comment', sa.Text(length=20000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_homes_title'), 'homes', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_homes_title'), table_name='homes')
    op.drop_table('homes')
    # ### end Alembic commands ###
